services:
  db:
    image: postgres:17-alpine
    container_name: pethub-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p37hvb_p455
      POSTGRES_DB: pethub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pethub-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pethub.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: